/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ms3.challenge;

import java.util.Scanner;
import java.io.*;

public class App {
    private static int totalRecords = 0;
    private static int successfulRecords = 0;
    private static int failedRecords = 0;
    private static final String COMMAREGEX = ",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)";

    public static void main(String args[]) throws Exception {
        Scanner input = new Scanner(System.in);
        System.out.println("Input File: ");
        String inputFile = input.nextLine();

        Scanner sc = new Scanner(new File("./src/input/" + inputFile + ".csv"));
        BadRecord badRecords = new BadRecord("./src/output/" + inputFile + "-bad.csv");
        Logger logs = new Logger("./src/output/" + inputFile + ".log");
        Database db = new Database(inputFile, "records");

        while(sc.hasNext()) {
            String line = sc.nextLine();
            totalRecords++;
            if(validateRecord(line)) {
                db.addRecord(line.split(COMMAREGEX));
                successfulRecords++;
            } else {
                badRecords.writeBadRecord(line);
                failedRecords++;
            }
        }
        sc.close();
        db.close();
        String run = "# of records received: " + totalRecords + " | # of records successful: " + successfulRecords + " | # of records failed: " + failedRecords;
        logs.logRun(run);

        input.close();
        logs.close();
        badRecords.close();
    }

    public static boolean validateRecord(String record) {
        String[] entries = record.split(COMMAREGEX);
        for(String entry : entries)
            if(entry.equals(""))
                return false;
        if(entries.length != 10)
            return false;
        return true;
    }
}